const sentence = [
  "Halloween",
  "ANDORRA",
  "HAMPSHIRE",
  "abundant",
  "awesome",
  "beloved",
  "blessed",
  "cooperation",
  "brilliant",
  "calm",
  "centered",
  "cheerful",
  "compassion",
  "courage",
  "brave",
  "create",
  "dance",
  "deserving",
  "empathetic",
  "dream",
  "excel",
  "enthusiastic",
  "fabulous",
  "flourish",
  "forgive",
  "freedom",
  "friendship",
  "fun",
  "generous",
  "grateful",
  "energetic",
  "grow",
  "happy",
  "heartwarming",
  "marvelous",
  "inspired",
  "innovative",
  "kind",
  "laugh",
  "learn",
  "healthy",
  "natural",
  "nurture",
  "original",
  "positive",
  "loveable",
  "present",
  "imagine",
  "radiant",
  "relax",
  "joyful",
  "peaceful",
  "powerful",
  "prosper",
  "prosperous",
  "purpose",
  "refresh",
  "optimistic",
  "resourceful",
  "love",
  "spirited",
  "quality",
  "successful",
  "talented",
  "Vital",
  "viBrant",
  "soulFUL",
  "upBeat",
  "sweetheart",
  "worthy",
  "smiley",
  "true-blue",
  "smart",
  "secure",
  "treasure",
  "vivaceous",
  "thrive",
  "wise",
  "estimated",
  "yesterday",
  "bombarded",
  "Worcestershire",
  "Choir",
  "Sixth",
  "pronounce",
  "Otorhinolaryngologist",
  "Colonel",
  "Penguin",
  "Isthmus",
  "Anemone",
  "Squirrel",
  "pronunciations",
  "Fairy",
  "Bengaluru",
  "corona",
  "pandemic",
  "pangolins",
  "snake",
  "cacke",
  "pizza",
  "ymedialabs",
];
const hangmanWords = [
  {
    topic: "Halloween",
    clue: "",
    answer: "SPOOKY",
  },
  {
    topic: "Words in language teaching",
    clue: "",
    answer: "VOWEL",
  },
  {
    topic: "Presidents of the USA",
    clue: "",
    answer: "GROVERCLEVELAND",
  },
  {
    topic: "Sports",
    clue: "",
    answer: "STREETBALL",
  },
  {
    topic: "European countries",
    clue: "",
    answer: "ANDORRA",
  },
  {
    topic: "English counties, shires",
    clue: "",
    answer: "HAMPSHIRE",
  },
  {
    topic: "Animals",
    clue: "a prime suspect",
    answer: "PANGOLIN",
  },
  {
    topic: "Drinks",
    clue: "",
    answer: "COFFEE",
  },
  {
    topic: "Clothes",
    clue: "",
    answer: "SOCKS",
  },
  {
    topic: "Riddles",
    clue: "What begins with an “e” and only contains one letter?",
    answer: "ENVELOPE",
  },
  {
    topic: "Riddles",
    clue: "What is 3/7 chicken, 2/3 cat and 2/4 goat",
    answer: "CHICAGO",
  },
  {
    topic: "Riddles",
    clue: "What is so fragile that saying its name breaks it",
    answer: "SILENCE",
  },
  {
    topic: "Movies",
    clue: "From 1970's, and its sequel, The Two *****, was released in 1990",
    answer: "CHINATOWN",
  },
  {
    topic: "Movies",
    clue: "Guess this and you are a freeman",
    answer: "SE7EN",
  },
  {
    topic: "Movies",
    clue: "A free and open-source transcompiler",
    answer: "BABEL",
  },
  {
    topic: "Movies",
    clue: "But he is Hero",
    answer: "ZERO",
  },
  {
    topic: "Movies",
    clue: "Every one has a story",
    answer: "KAHAANI",
  },
  {
    topic: "Movies",
    clue: "From 1990's, and my name is khan",
    answer: "BAAZIGAR",
  },
];
export { hangmanWords, sentence };
